'use client'
import {useEffect,useState} from 'react'
import {api} from '../../lib/api'
export default function Admin(){
 const [me,setMe]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[cal,setCal]=useState<any[]>([]),[err,setErr]=useState('')
 async function load(){try{const m=await api('/api/auth/me');setMe(m.user);if(m.user.role!=='admin')throw new Error('Admin only');const [u,r,c]=await Promise.all([api('/api/admin/users'),api('/api/admin/reports'),api('/api/admin/calibration')]);setUsers(u.users);setReports(r.reports);setCal(c.items)}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load()},[])
 async function toggle(u:any){await api(`/api/admin/users/${u.id}/disable?disabled=${!u.disabled}`,{method:'POST'});load()}
 async function reset(u:any){const p=prompt(`Password baru untuk @${u.username} (min. 8 karakter)`);if(!p)return;await api(`/api/admin/users/${u.id}/reset-password`,{method:'POST',body:JSON.stringify({password:p})});alert('Password direset dan semua sesi login user tersebut dicabut.')}
 async function quarantine(sig:string,active:boolean){await api(`/api/admin/quarantine/${sig}?active=${active}`,{method:'POST'});load()}
 async function cleanup(){const d=await api('/api/admin/maintenance',{method:'POST'});alert(JSON.stringify(d.cleanup));}
 const highSignal=cal.filter((x:any)=>x.attempts>=5).sort((a:any,b:any)=>Math.abs(b.empirical_level-b.authored_level)-Math.abs(a.empirical_level-a.authored_level)).slice(0,30)
 return <main style={{maxWidth:1100,margin:'40px auto',padding:20,fontFamily:'system-ui'}}><a href="/">← Kembali ke UPKP Coach</a><h1>Admin Console</h1>{err?<p>{err}</p>:<>
 <div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><p style={{flex:1}}>User recovery, content quality, empirical calibration, dan maintenance.</p><button onClick={cleanup}>Cleanup expired data</button></div>
 <h2>Users</h2><div style={{display:'grid',gap:10}}>{users.map(u=><div key={u.id} style={{background:'white',border:'1px solid #dfe5ee',borderRadius:12,padding:14,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><b>@{u.username}</b><div style={{fontSize:12,color:'#71809b'}}>{u.role} · {u.attempts} attempts · {u.disabled?'DISABLED':'active'}</div></div><div style={{display:'flex',gap:7}}><button onClick={()=>reset(u)}>Reset password</button>{u.id!==me?.id&&<button onClick={()=>toggle(u)}>{u.disabled?'Enable':'Disable'}</button>}</div></div>)}</div>
 <h2 style={{marginTop:34}}>Question reports</h2>{reports.length===0?<p>Belum ada laporan.</p>:<div style={{display:'grid',gap:8}}>{reports.slice(0,50).map((r:any,i)=><div key={i} style={{border:'1px solid #dfe5ee',borderRadius:10,padding:12}}><b>{r.reason}</b> · @{r.username}<div style={{fontSize:12,color:'#71809b'}}>{r.signature} · {r.question_id} · reports {r.report_count}</div>{r.detail&&<p>{r.detail}</p>}<button onClick={()=>quarantine(r.signature,!r.quarantined)}>{r.quarantined?'Release':'Quarantine'}</button></div>)}</div>}
 <h2 style={{marginTop:34}}>Empirical difficulty watch</h2><p style={{color:'#71809b'}}>Menonjolkan item yang authored level-nya berbeda jauh dari perilaku nyata user. Data kecil belum cukup untuk keputusan otomatis.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">Skill</th><th>N</th><th>Authored</th><th>Empirical</th><th>Accuracy</th><th>Skip</th><th>Mean</th></tr></thead><tbody>{highSignal.map((x:any)=><tr key={x.signature}><td>{x.skill}</td><td align="center">{x.attempts}</td><td align="center">{x.authored_level}</td><td align="center">{x.empirical_level}</td><td align="center">{Math.round(x.accuracy*100)}%</td><td align="center">{Math.round(x.skip_rate*100)}%</td><td align="center">{Math.round(x.mean_ms/1000)}s</td></tr>)}</tbody></table></div>
 </>}</main>}
