"""Expanded bimbel-style teaching modules layered on top of the concise core notes."""

MODULES = {
  "padanan": "## Kelas bimbel: padanan, antonim, dan analogi\n### Cara berpikir\nJangan memilih opsi yang sekadar terasa dekat. Tetapkan dulu arti sederhana atau hubungan antar-kata, baru cocokkan ke pilihan.\n### Metode\n1. Tentukan kelas kata dan konteks.\n2. Ucapkan definisi dengan bahasa sendiri.\n3. Coret opsi yang hanya satu topik tetapi bukan satu makna.\n4. Untuk analogi, ubah A:B menjadi satu kalimat hubungan.\n### Contoh terbimbing\nRelatif berarti tidak mutlak atau bergantung pembanding. Jika ada opsi nisbi, absolut, tetap, khusus, maka nisbi paling tepat.\n### Jebakan\nKata yang sering muncul bersama belum tentu sinonim. Pada analogi, arah relasi juga harus sama.\n### Target ujian\nSebelum melihat opsi akhir, kamu harus bisa menyebut definisi atau relasinya.",
  "kelompok": "## Kelas bimbel: pengelompokan kata\n### Ide utama\nEmpat item berbagi satu kategori yang cukup spesifik; satu item tidak.\n### Metode\nBangun kategori dari empat kata yang paling dikenal. Uji apakah kategori itu juga mencakup item kelima. Jika iya, kategorinya terlalu luas.\n### Contoh terbimbing\nApel, mangga, jeruk, wortel, pisang. Kategori buah memuat empat item dan mengecualikan wortel.\n### Jebakan\nKategori terlalu umum, memaksa kemiripan dangkal, atau panik karena satu istilah tidak dikenal.\n### Target ujian\nMampu melengkapi kalimat: empat kata ini sama karena ...",
  "silogisme": "## Kelas bimbel: silogisme dan conditional logic\n### Fondasi\nBedakan kesimpulan yang pasti dari yang hanya mungkin. Semua A adalah B tidak berarti semua B adalah A.\n### Translasi cepat\nSemua A adalah B → A berada di dalam B. Tidak ada A yang B → tidak beririsan. Sebagian A adalah B → minimal ada satu irisan.\n### Conditional\nP→Q setara dengan kontraposisi bukan-Q→bukan-P. Q benar tidak membuktikan P; P salah tidak membuktikan Q salah.\n### Contoh terbimbing\nSemua analis adalah pegawai. Sebagian pegawai auditor. Tidak wajib benar bahwa sebagian analis auditor.\n### Target ujian\nMampu menolak kesimpulan yang terdengar masuk akal tetapi tidak dijamin premis.",
  "analisis": "## Kelas bimbel: penalaran analitis\n### Prinsip\nPindahkan semua aturan dari kepala ke representasi: urutan, slot, tabel, atau pasangan.\n### Langkah\n1. Daftar variabel.\n2. Tandai aturan absolut.\n3. Bentuk blok untuk aturan tepat bersebelahan.\n4. Gabungkan constraints.\n5. Baru uji pertanyaan.\n### Contoh\nA sebelum B, C tepat setelah A, B sebelum D → blok A-C berada sebelum B dan D.\n### Jebakan\nTidak membedakan sebelum dan tepat sebelum; menguji semua permutasi dari nol.\n### Target ujian\nSetiap soal punya skema kerja yang terlihat, bukan reasoning mental penuh.",
  "operasi": "## Kelas bimbel: operasi bilangan\n### Number sense\nSebelum menghitung, cari simplifikasi, faktor, atau estimasi.\n### Contoh\n48×25 = 48×100/4 = 1200. Lebih aman dan cepat daripada perkalian panjang.\n### Benchmark penting\n1/2=50%, 1/4=25%, 1/5=20%, 1/8=12,5%, 1/3≈33,3%.\n### Jebakan\nUrutan operasi, tanda negatif, aturan pangkat, dan penyederhanaan akar yang tidak sah.\n### Target ujian\nMampu membuang opsi mustahil lewat estimasi sebelum hitung presisi.",
  "persamaan": "## Kelas bimbel: persamaan dan pertidaksamaan\n### Pilih metode dari bentuk\nEliminasi bila koefisien mudah disamakan; substitusi bila satu variabel mudah diisolasi.\n### Kuadrat\nCek faktorisasi sebelum rumus abc. Untuk jumlah/hasil kali akar, gunakan Vieta langsung.\n### Contoh\nx²−7x+10=0 → (x−5)(x−2)=0 → akar 5 dan 2.\n### Pertidaksamaan\nKali/bagi bilangan negatif membalik tanda. Untuk kuadrat, gunakan akar dan garis bilangan.\n### Target ujian\nTidak memakai metode panjang ketika struktur soal menyediakan jalan singkat.",
  "geometri": "## Kelas bimbel: geometri\n### Cara kerja\nGambar → tandai hubungan → samakan satuan → baru pilih rumus.\n### Contoh\nPersegi panjang 6×8 memiliki diagonal 10 karena pola 6-8-10.\n### Scaling\nJika panjang dan lebar naik 10%, luas naik 1,1²=1,21 atau 21%, bukan 20%.\n### Jebakan\nKeliru membedakan luas, keliling, volume, diagonal; satuan tidak konsisten.\n### Target ujian\nBisa menjelaskan mengapa rumus tertentu berlaku pada gambar tersebut.",
  "aritsos": "## Kelas bimbel: aritmatika sosial dan deret\n### Persentase sebagai faktor\nNaik p% → kali 1+p. Turun p% → kali 1−p. Perubahan bertahap dikalikan, bukan dijumlah.\n### Contoh\nDiskon 20% lalu 10% → faktor 0,8×0,9=0,72 → diskon efektif 28%.\n### Untung-rugi\nPastikan denominator: persentase untung/rugi biasanya terhadap harga beli.\n### Barisan\nBedakan nilai suku Un dengan jumlah sampai suku Sn.\n### Target ujian\nTerjemahkan cerita menjadi model sebelum menyentuh kalkulasi.",
  "sudut": "## Kelas bimbel: sudut dan himpunan\n### Sudut jam\nJarum jam bergerak 0,5° per menit; jarum menit 6° per menit. Gunakan |30h−5,5m| lalu ambil sudut terkecil.\n### Himpunan\nn(A∪B)=n(A)+n(B)−n(A∩B). Isi irisan dulu sebelum bagian hanya-A/hanya-B.\n### Contoh\n40 orang; 25 suka A, 20 suka B, 10 keduanya → minimal salah satu =35.\n### Jebakan\nMenghitung intersection dua kali atau mencampur orang di luar kedua himpunan.\n### Target ujian\nSelalu gambar skema mini.",
  "banding": "## Kelas bimbel: rasio, work rate, reverse percentage\n### Rasio\nA:B=2:3 dan total 25 → satu bagian 5 → A=10, B=15.\n### Work rate\nJika A selesai 6 hari, rate A=1/6 pekerjaan/hari. Gabungan pekerja menjumlahkan rate.\n### Reverse percentage\nNilai setelah naik 25% menjadi 100 → nilai awal 100/1,25=80.\n### Jebakan\nMengurangi 25% dari nilai akhir atau menjumlahkan waktu kerja.\n### Target ujian\nKenali dulu model: rasio, rate, atau faktor perubahan.",
  "jarak": "## Kelas bimbel: jarak, kecepatan, waktu\n### Relative speed\nBerpapasan → kecepatan dijumlah. Menyusul → kecepatan dikurang.\n### Contoh\nJarak 180 km, dua kendaraan 60 dan 30 km/jam saling mendekat → 180/(60+30)=2 jam.\n### Rata-rata\nKecepatan rata-rata = total jarak/total waktu, bukan rata-rata sederhana kecepatan.\n### Jebakan\nMenit belum diubah ke jam; waktu berhenti; salah kerangka acuan.\n### Target ujian\nTentukan mendekat, menjauh, atau mengejar sebelum rumus.",
  "peluang": "## Kelas bimbel: peluang, permutasi, kombinasi\n### Pertanyaan pertama\nApakah urutan penting? Jika iya, permutasi. Jika hanya memilih anggota, kombinasi.\n### Komplemen\nUntuk minimal satu kejadian, sering lebih cepat gunakan 1−P(tidak ada).\n### Contoh\nMinimal satu angka 6 dari dua dadu =1−(5/6)²=11/36.\n### Jebakan\nSalah asumsi independen, pengembalian/tanpa pengembalian, atau ruang sampel.\n### Target ujian\nTulis struktur ruang sampel sebelum menghitung.",
  "statistika": "## Kelas bimbel: statistika dan interpretasi data\n### Kerja lewat total\nTotal = rata-rata × banyak data.\n### Contoh\n8 orang rata-rata 75 → total 600. Masuk nilai 84 → total 684, mean baru 76.\n### Weighted average\nBobot masuk numerator dan denominator. Jangan merata-ratakan dua mean dengan ukuran kelompok berbeda.\n### Data visual\nPeriksa unit, sumbu, skala, baseline, dan periode.\n### Target ujian\nCari total tersembunyi sebelum hitung.",
  "deret": "## Kelas bimbel: deret angka dan huruf\n### Urutan diagnosis\nSelisih pertama → selisih kedua → rasio → pola ganjil/genap → rekursif → kuadrat/kubik/prima.\n### Contoh\n2,5,10,17,26 → selisih 3,5,7,9 → berikut +11 =37.\n### Alternating\nPisahkan posisi ganjil dan genap menjadi dua deret kecil.\n### Jebakan\nMemaksa pola kompleks sebelum mencoba pola sederhana.\n### Target ujian\nBatasi waktu diagnosis; jika buntu, parkir dan kembali.",
  "deretfig": "## Kelas bimbel: deret figural\n### Jadikan gambar sebagai data\nLacak atribut: jumlah, posisi, orientasi, warna/isi, ukuran, dan relasi.\n### Metode\nTanyakan apa yang berubah dan apa yang tetap pada setiap transisi.\n### Contoh\nObjek berputar 90° sambil jumlah titik bertambah satu: kedua aturan harus diterapkan bersamaan.\n### Jebakan\nMenganggap refleksi sama dengan rotasi.\n### Target ujian\nSebut aturan transformasi dengan kata-kata sebelum memilih opsi.",
  "analogifig": "## Kelas bimbel: analogi figural\n### Model operator\nCari operasi yang mengubah A menjadi B, lalu terapkan operasi yang sama pada C.\n### Checklist\nRotasi, refleksi, translasi, perubahan jumlah, perubahan fill, pertukaran luar-dalam.\n### Teknik eliminasi\nPeriksa atribut paling diskriminatif dulu agar beberapa opsi gugur sekaligus.\n### Jebakan\nMencari kemiripan visual tanpa mendefinisikan transformasi.\n### Target ujian\nBisa merumuskan aturan seperti rotasi 90° + invert fill.",
  "etika": "## Kelas bimbel TSKKWK: etika ASN dan perilaku pegawai\n### Fondasi resmi\nUU 20/2023 menempatkan profesionalitas, netralitas, pelayanan publik, dan pemerintahan yang bersih sebagai karakter ASN. Dalam konteks Kemenkeu, PMK 190/PMK.01/2018 menjadi anchor kode etik dan kode perilaku.\n### Metode soal kasus\n1. Identifikasi konflik kepentingan.\n2. Pisahkan yang nyaman dari yang benar.\n3. Cari tindakan yang paling transparan dan melalui jalur resmi.\n4. Uji apakah tindakan menjaga kepentingan publik dan organisasi.\n### Contoh\nHadiah dari pihak yang baru selesai dilayani tetap harus dinilai kaitannya dengan jabatan/layanan; jangan menganggap aman hanya karena diberikan sesudah proses selesai.\n### Jebakan\nLoyalitas kepada atasan bukan berarti menaati perintah yang bertentangan dengan hukum/etika. Menjaga nama baik bukan berarti menutup pelanggaran.\n### Target ujian\nPilih tindakan yang defensible jika seluruh faktanya diaudit.",
  "wawasan": "## Kelas bimbel TSKKWK: wawasan kebangsaan\n### Empat jangkar\nPancasila, UUD NRI 1945, NKRI, dan Bhinneka Tunggal Ika.\n### Cara belajar\nHubungkan setiap prinsip dengan contoh kasus: definisi → perilaku dan kasus → prinsip.\n### Area wajib\nTujuan negara dalam Pembukaan UUD 1945, negara hukum, kedaulatan rakyat, hak dan kewajiban warga negara, persatuan, bela negara, toleransi, dan keberagaman.\n### Contoh\nPerbedaan keyakinan dalam tim tidak boleh menjadi dasar perlakuan berbeda; analisis dengan martabat manusia, persatuan, dan prinsip negara hukum.\n### Jebakan\nHafal slogan tetapi tidak mampu memilih tindakan yang sesuai dalam kasus.",
  "nilai": "## Kelas bimbel TSKKWK: Nilai-Nilai Kementerian Keuangan\n### Lima nilai\nIntegritas, Profesionalisme, Sinergi, Pelayanan, Kesempurnaan.\n### Bedakan dari perilaku dominan\nIntegritas: benar dan dapat dipercaya. Profesionalisme: kompeten, akurat, tuntas. Sinergi: kolaborasi. Pelayanan: kebutuhan stakeholder. Kesempurnaan: perbaikan dan inovasi.\n### Contoh\nMemperbaiki proses agar kesalahan tidak berulang → Kesempurnaan. Menyelesaikan pekerjaan dengan standar tinggi → Profesionalisme. Solusi lintas unit → Sinergi.\n### Teknik ujian\nCari kata kerja dan tujuan utama kasus; semua opsi bisa terdengar positif, tetapi satu nilai biasanya paling dominan.\n### Target ujian\nBisa membedakan nilai berdasarkan perilaku, bukan hafalan akronim.",
  "kepegawaian": "## Kelas bimbel TSKKWK: kepegawaian dan disiplin\n### Peta regulasi\nUU 20/2023 tentang ASN; PP 94/2021 tentang Disiplin PNS; PMK 123/2023 untuk pemeriksaan pelanggaran dan penjatuhan hukuman disiplin di Kemenkeu; Peraturan BKN 24/2017 jo. 7/2021 untuk cuti PNS.\n### Tiga lapis soal\nSubstansi pelanggaran → proses pemeriksaan → konsekuensi/hukuman.\n### Disiplin\nJangan menentukan hukuman hanya dari satu kata dalam kasus. Baca jenis pelanggaran, fakta, durasi, dan kewenangan.\n### Cuti\nPahami tujuan dan logika tiap jenis cuti. Untuk angka/detail kewenangan yang spesifik, pegang regulasi resmi terbaru.\n### Jebakan\nMenggunakan UU 5/2014 sebagai dasar utama setelah digantikan UU 20/2023.\n### Target ujian\nMampu memisahkan aturan ASN umum, disiplin PNS, dan prosedur internal Kemenkeu.",
  "keuangan": "## Kelas bimbel TSKKWK: pengelolaan keuangan negara\n### Tiga pilar\nUU 17/2003: ruang lingkup/prinsip dan pengelolaan keuangan negara. UU 1/2004: perbendaharaan dan pelaksanaan. UU 15/2004: pemeriksaan oleh BPK.\n### Peta siklus\nPerencanaan → penganggaran → pelaksanaan → penatausahaan → pelaporan/pertanggungjawaban → pemeriksaan → tindak lanjut.\n### Aktor\nBedakan Menteri Keuangan sebagai pengelola fiskal, menteri/pimpinan lembaga sebagai pengguna anggaran/barang, pejabat perbendaharaan, dan BPK sebagai pemeriksa eksternal.\n### Contoh\nPertanyaan tentang pemeriksaan eksternal pengelolaan dan tanggung jawab keuangan negara mengarah ke BPK.\n### Jebakan\nMencampur pengelolaan, pengawasan internal, dan pemeriksaan eksternal.\n### Target ujian\nBisa memetakan kegiatan ke tahap siklus dan aktor yang tepat.",
  "struktur": "## Kelas bimbel TSKKWK: struktur Kementerian Keuangan terkini\n### Baseline current\nGunakan PMK 124/2024 sebagaimana diubah PMK 117/2025. Jangan lagi menggunakan PMK 118/2021 sebagai struktur aktif.\n### Cara belajar\nUntuk setiap unit kuasai nama, domain tugas, contoh isu, dan unit yang paling mudah tertukar.\n### Kelompok fungsi\nBedakan dukungan kementerian, pengawasan internal, strategi/fiskal, anggaran, penerimaan, perbendaharaan, kekayaan negara, perimbangan, pembiayaan/risiko, sektor keuangan, teknologi/data, dan pendidikan/pembelajaran.\n### Jebakan\nNama unit lama setelah reorganisasi.\n### Target ujian\nDiberi satu isu, kamu bisa memilih unit paling relevan tanpa hanya mengandalkan singkatan."
}

def expand(code, base):
    extra=MODULES.get(code, "")
    return (base.strip()+"\n\n"+extra.strip()).strip() if extra else base
